---
- name: My first playbook
  hosts: all
  remote_user: test
  gather_facts: false

  tasks:
    - name: Touch file
      ansible.builtin.file:
        path: /tmp/foo.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
