
---
- name: My first playbook
  hosts: all
  remote_user: test
  gather_facts: true
  become: true

  tasks:
    - name: Вывод дистрибутива
      ansible.builtin.debug:
        msg: "Дистрибутив: {{ ansible_distribution }}"

    - name: Установка Nginx на CentOS с использованием yum
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Установка Nginx на Ubuntu с использованием apt
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_distribution == 'Ubuntu'
    
    - name: Копирование конфига
      ansible.builtin.copy:
        src: temp.txt
        dest: /tmp/temp2.txt
        owner: test
        group: test
        mode: '0644'

    - name: Выставляем переменные
      ansible.builtin.set_fact:
        my_var: 1
        my_other_var: "hello"

    - name: Создание конфига из шаблона
      ansible.builtin.template:
        src: template.j2
        dest: /tmp/temp3.txt