---
- name: My first playbook
  hosts: all
  gather_facts: no
  tasks:
  
  - name: Ignore errors
    ansible.builtin.command: /bin/fail
    ignore_unreachable: true
    ignore_errors: true

  - name: Define my own failure
    ansible.builtin.command: "echo FAILED"
    register: command_result
    failed_when: "'FAILED' in command_result.stdout"